micronaut:
  application:
    name: graphql-gateway

  security:
    enabled: true
    intercept-url-map:
      - pattern: /graphiql
        access:
          - isAnonymous()
      - pattern: /graphql
        access:
          - isAnonymous()

    authentication: bearer
    token:
      jwt:
        enabled: true
    oauth2:
      clients:
        keycloak:
          grantType: password
          clientId: micronaut
          clientSecret: 6i2jVunYzcXKHyYbb9Kpn6gIZzdRHA59
          token:
            url: ${keycloak.host}/auth/realms/${keycloak.realm}/protocol/openid-connect/token
            auth-method: client_secret_post

keycloak:
  host: "http://localhost:8888"
  realm: master

graphql:
  instrumentation:
    maxDepth: 3
    maxComplexity: 500
  graphiql:
    enabled: true

netty:
  default:
    allocator:
      max-order: 3