#include postgres-osm, logback-template, bootstrap, kubernetes, redis

micronaut:
  application:
    name: regions

flyway:
  datasources:
    osm:
      enabled: false
      locations:
        - classpath:/db/regions/migration

kafka:
  enabled: false