#include postgres-default, postgres-keycloak, postgres-osm, logback-template, kafka, keycloak-security, redis, bootstrap, dadata

jackson:
  serializationInclusion: ALWAYS

micronaut:
  application:
    name: api-tests
    simulate-remote-routing: true
  security:
    enabled: true

graphql:
  graphql-ws:
    enabled: true
    path: /graphql-ws
    keep-alive-interval: 15s
    connection-init-wait-timeout: 5s
  instrumentation:
    maxComplexity: 500
    maxDepth: 15
  graphiql:
    enabled: true
    version: 4.1.2
    explorer-plugin-version: 4.0.6

flyway:
  datasources:
    default:
      enabled: false
      baseline-on-migrate: true
      locations:
        - classpath:/db/library/migration
    keycloak:
      enabled: false
      baseline-on-migrate: true
      locations:
        - classpath:/db/keycloak/migration
    osm:
      enabled: false
      baseline-on-migrate: true
      locations:
        - classpath:/db/regions/migration
