#include postgres-keycloak, logback-template, bootstrap, kafka, kubernetes, redis, keycloak, dadata

micronaut:
  application:
    name: organization-management

flyway:
  datasources:
    keycloak:
      enabled: false
      baseline-on-migrate: true
      locations:
        - classpath:/db/keycloak/migration