#include keycloak

micronaut:
  security:
    enabled: true
    intercept-url-map:
      - pattern: /
        access:
          - isAnonymous()
      - pattern: /graphiql
        access:
          - isAnonymous()
      - pattern: /graphql
        access:
          - isAnonymous()
      - pattern: /graphql-ws
        access:
          - isAnonymous()
      - pattern: /oauth/login/keycloak
        access:
          - isAnonymous()
      - pattern: /events
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true

    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          clientId: ${this@keycloak.clientId}
          clientSecret: ${this@keycloak.clientSecret}
          scopes:
            - openid
            - email
            - phone
            - roles
          token:
            url: ${this@keycloak.baseUri}/protocol/openid-connect/token
          openid:
            registration:
              url: ${this@keycloak.baseUri}/protocol/openid-connect/registrations
            authorization:
              prompt: select_account
            issuer: '${this@keycloak.baseUri}'
    endpoints:
      logout:
        get-allowed: true
