application:
  backend: localhost

server:
  port: 8888

spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:postgresql://${application.backend}:5432/keycloak
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1

logging:
  level:
    org.jgroups: INFO
    org.infinispan: INFO
    org.keycloak: INFO
    org.keycloak.services.managers.DefaultBruteForceProtector: DEBUG
    org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner: DEBUG
    org.keycloak.services.managers.UserSessionManager: DEBUG
    org.keycloak.timer.basic: DEBUG
