#include logback-template, bootstrap, keycloak, keycloak-security, redis

# strictly required for graphql introspection
# otherwise empty lists wouldn't be serialized
jackson:
  serializationInclusion: ALWAYS

micronaut:
  application:
    name: graphql-gateway

  security:
    enabled: false

application:
  rsocket:
    enabled: false

graphql:
  instrumentation:
    maxDepth: 15
    maxComplexity: 500
  graphiql:
    enabled: true

netty:
  default:
    allocator:
      max-order: 3

kafka:
  enabled: false
