datasources:
  osm:
    url: jdbc:postgresql://${datasources.osm.host}:${datasources.osm.port}/nominatim
    username: nominatim
    password: qaIACxO6wMR3

test-resources:
  containers:
    nominatim:
      env:
        - PBF_PATH: "/nominatim/data/andorra-latest.osm.pbf"
      exposed-ports:
        - datasources.osm.port: 5432
      hostnames:
        - datasources.osm.host
      image-name: mediagis/nominatim:4.4
      rw-fs-bind:
        - src/test/resources/pbf/andorra-latest.osm.pbf: /nominatim/data/andorra-latest.osm.pbf
      wait-strategy:
        log:
          regex: ".*Nominatim\ is\ ready\ to\ accept\ requests.*"
