keycloak:
  serverUrl: http://dunedain.box:8888
  realm: master
  username: admin@loopback
  password: admin
  clientId: micronaut
  clientSecret: UCcbKWfOJjRLoufnVf2Zr1yxoceeLjWs
  baseUri: ${this@keycloak.serverUrl}/realms/${this@keycloak.realm}
