#include postgres, logback-template, bootstrap-template

micronaut:
  application:
    name: library
  server:
    port: 8081

flyway:
  datasources:
    default:
      enabled: false
      locations:
        - classpath:/db/library/migration
