#include postgres-default, logback-template, bootstrap, kafka, kubernetes, redis

micronaut:
  application:
    name: library

flyway:
  datasources:
    default:
      enabled: false
      locations:
        - classpath:/db/library/migration
