redis:
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  caches:
    jimmer:
      expire-after-write: 10m
      value-serializer: io.eordie.multimodule.common.utils.ProtobufObjectSerializer
    dataloader:
      expire-after-write: 1d
      value-serializer: io.eordie.multimodule.common.utils.ProtobufObjectSerializer
    oauth2:
      expire-after-write: 30d
      value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
